name: New tag, new version

on:
  push:
    tags:
      - 'v*'

jobs:
  add-new-version:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: setting ${{github.ref_name}} as latest version
      CI_COMMIT_AUTHOR: ${{ github.event.repository.name }} CI
    steps:
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: create a new latest version
      run: |
        rm -f latest
        t=${{github.ref_name}}
        ln -s ${t%.*}.x latest
        
    - name: test if latest is effectively changed
      uses: technote-space/get-diff-action@v3
      id: git_diff
      with:
          FILES: latest
          
    - name: push the change if necessary
      if: steps.git_diff.outputs.diff
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "iximiel@users.noreply.github.com"
        git add latest || exit 0
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
  #force the deploy after the creation of the folder
  deploy:
    needs: add-new-version
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
    
