name: New tag, new version

on:
  push:
    tags:
      - 'v*'

jobs:
  update-gh-page:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: setting ${{github.ref_name}} as latest version
      CI_COMMIT_AUTHOR: ${{ github.event.repository.name }} CI
    steps:
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: create a new latest version
      run: |
        rm -f latest
        t=${{github.ref_name}}
        ln -s ${t%.*}.x latest
    - name: push the change
       run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "iximiel@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push

      
